In [1]:
import pandas as pd

df = pd.read_csv("dataset.csv")
df

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f142,f143,f144,f145,f146,f147,f148,f149,f150,target
0,-0.924357,-0.326536,-1.875007,-1.780626,-0.630143,0.788204,2.792209,-0.772192,-0.450994,0.400000,...,0.968645,-0.702053,-0.327662,-0.392108,-1.463515,0.296120,0.261055,0.005113,-0.234587,10.681366
1,0.001795,-1.285599,-0.726774,0.385711,0.891863,0.599451,-0.140553,-0.761760,0.117707,0.333231,...,0.856399,0.214094,-1.245739,0.173181,0.385317,-0.883857,0.153725,0.058209,-1.142970,-60.163343
2,0.956702,2.319330,-0.705012,0.081829,0.330880,0.838491,2.493000,1.227669,-0.785989,-0.920674,...,-0.493001,-0.589365,0.849602,0.357015,-0.692910,0.899600,0.307300,0.812862,0.629629,131.226545
3,-0.982294,0.190424,1.082691,0.714610,-1.907808,0.224216,0.156973,0.556553,0.058984,-1.397118,...,0.491919,-1.320233,1.831459,1.179440,-0.469176,-1.713135,1.353872,-0.114540,1.237816,-131.889020
4,-0.057061,-0.592465,-2.850030,-1.935430,2.002427,-1.012644,1.059950,-1.000629,0.141596,-0.642776,...,1.479944,0.077368,-0.861284,1.523124,0.538910,-1.037246,-0.190339,-0.875618,-1.382800,-138.566956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1.146487,-0.339530,-2.508957,0.252195,-0.384182,0.184859,-0.770425,0.613266,-1.112327,-0.166815,...,-0.960417,1.565103,0.500333,-0.774601,-0.993825,0.307204,0.044206,0.832110,0.546968,-18.681830
196,-0.357029,-1.091701,0.534506,-2.153343,1.051948,-0.526035,0.420973,1.995667,0.890383,0.497743,...,0.138976,0.417681,0.093365,-0.659427,0.004001,-0.714387,-0.780377,-0.336150,-0.119423,234.589644
197,0.099314,0.023081,-2.367478,0.309727,-0.220018,-1.680870,0.395599,0.633225,-0.390409,-0.948749,...,-0.519942,1.021659,0.059655,-0.163061,0.756115,-0.531876,-0.286706,0.670167,-0.031396,-94.329646
198,-0.051119,0.030476,-0.111319,0.520689,0.257253,0.466431,-0.702911,-0.545087,0.016125,-2.707544,...,-2.205935,-0.733608,-0.725518,1.187127,-1.113844,0.226657,-0.128128,1.043043,0.595832,80.152034
199,-0.592464,-0.562168,0.288694,-0.088363,-0.646227,-0.109610,0.006422,1.000582,-0.026406,-1.748532,...,-0.468661,0.888839,0.902492,0.952591,0.387827,1.377367,0.378354,1.713530,-1.619920,110.131842

In [2]:
X = df.drop('target', axis=1)
X.head()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f141,f142,f143,f144,f145,f146,f147,f148,f149,f150
0,-0.924357,-0.326536,-1.875007,-1.780626,-0.630143,0.788204,2.792209,-0.772192,-0.450994,0.400000,...,0.097078,0.968645,-0.702053,-0.327662,-0.392108,-1.463515,0.296120,0.261055,0.005113,-0.234587
1,0.001795,-1.285599,-0.726774,0.385711,0.891863,0.599451,-0.140553,-0.761760,0.117707,0.333231,...,-0.446515,0.856399,0.214094,-1.245739,0.173181,0.385317,-0.883857,0.153725,0.058209,-1.142970
2,0.956702,2.319330,-0.705012,0.081829,0.330880,0.838491,2.493000,1.227669,-0.785989,-0.920674,...,-0.208122,-0.493001,-0.589365,0.849602,0.357015,-0.692910,0.899600,0.307300,0.812862,0.629629
3,-0.982294,0.190424,1.082691,0.714610,-1.907808,0.224216,0.156973,0.556553,0.058984,-1.397118,...,-0.898415,0.491919,-1.320233,1.831459,1.179440,-0.469176,-1.713135,1.353872,-0.114540,1.237816
4,-0.057061,-0.592465,-2.850030,-1.935430,2.002427,-1.012644,1.059950,-1.000629,0.141596,-0.642776,...,-0.007973,1.479944,0.077368,-0.861284,1.523124,0.538910,-1.037246,-0.190339,-0.875618,-1.382800

In [3]:
y = df['target']
y.head()

0     10.681366
1    -60.163343
2    131.226545
3   -131.889020
4   -138.566956
Name: target, dtype: float64

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.7410632578788087

In [ ]:
from sklearn.linear_model import Lasso, Ridge

l1_model = Lasso(alpha=1.5)
l1_model.fit(X_train, y_train)
l1_model.score(X_test, y_test)

0.9900326923832247

In [10]:
l2_model = Ridge(alpha=1.5)
l2_model.fit(X_train, y_train)
l2_model.score(X_test, y_test)

0.943472358483948